In [1]:
import numpy as np
import torch

# Tensors

In [2]:
# Create a NumPy array
numpy_array = np.array([1.0, 2.0, 3.0, 4.0])

# Convert the NumPy array to a PyTorch tensor
tensor = torch.tensor(numpy_array)

print(tensor)

# Convert the PyTorch tensor to a NumPy array
numpy_array_back = tensor.numpy()

print(numpy_array_back, type(numpy_array_back))

tensor([1., 2., 3., 4.], dtype=torch.float64)
[1. 2. 3. 4.] <class 'numpy.ndarray'>


In [3]:
x = torch.randn(4, 4)

if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()
    print(z)

tensor([[ 0.3286,  0.3484, -0.4849,  0.0969],
        [ 1.2856,  2.8669,  1.5635, -0.2303],
        [ 0.7100,  0.4000,  0.3216,  2.4203],
        [ 1.7302,  1.0907,  0.0435,  1.0247]], device='cuda:0')


#### 1- Math Operations

In [4]:
import torch

# PyTorch tensors
a = torch.tensor([1, 2, 3], dtype=torch.float32)
b = torch.tensor([4, 5, 6], dtype=torch.float32)

# PyTorch operations
add = torch.add(a, b)
subtract = torch.subtract(a, b)
multiply = torch.multiply(a, b)
divide = torch.divide(a, b)

print("Add:", add)
print("Subtract:", subtract)
print("Multiply:", multiply)
print("Divide:", divide)

# Broadcasting in PyTorch
c = torch.tensor([1, 2, 3], dtype=torch.float32)
d = torch.tensor(2.0, dtype=torch.float32)
broadcast_mul = torch.multiply(c, d)

print("Broadcasting Multiplication:", broadcast_mul)

Add: tensor([5., 7., 9.])
Subtract: tensor([-3., -3., -3.])
Multiply: tensor([ 4., 10., 18.])
Divide: tensor([0.2500, 0.4000, 0.5000])
Broadcasting Multiplication: tensor([2., 4., 6.])


In [5]:
a = torch.tensor([1, 2, 3], dtype=torch.float32)

# PyTorch tensor creation functions
ones = torch.ones([2, 3])
zeros = torch.zeros([2, 3])
ones_like = torch.ones_like(a)
zeros_like = torch.zeros_like(a)
random_floats = torch.rand([2, 3])  # Random floats between 0 and 1
random_ints = torch.randint(0, 10, [2, 3])  # Random integers between 0 and 10

print("Ones:", ones, "\n")
print("Zeros:", zeros, "\n")
print("Ones like:", ones_like, "\n")
print("Zeros like:", zeros_like, "\n")
print("Random floats:", random_floats, "\n")
print("Random ints:", random_ints)

Ones: tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

Ones like: tensor([1., 1., 1.]) 

Zeros like: tensor([0., 0., 0.]) 

Random floats: tensor([[0.9308, 0.0866, 0.5007],
        [0.9581, 0.8422, 0.1053]]) 

Random ints: tensor([[4, 0, 6],
        [3, 5, 2]])


#### 2- Matrix Operations

In [6]:
import torch

# Define the matrices
matrix1 = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
matrix2 = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

# Matrix multiplication
matmul = torch.matmul(matrix1, matrix2)

# Transpose
transpose = torch.transpose(matrix1, 0, 1)

# Inverse (Only if the matrix is invertible)
inverse = torch.inverse(matrix1)

print("Matrix Multiplication:\n", matmul)
print("Transpose:\n", transpose)
print("Inverse:\n", inverse)

Matrix Multiplication:
 tensor([[19., 22.],
        [43., 50.]])
Transpose:
 tensor([[1., 3.],
        [2., 4.]])
Inverse:
 tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


#### 3- Reduction Operations

In [7]:
c = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)

sum_c = torch.sum(c)
mean_c = torch.mean(c)
max_c = torch.max(c)

print("Sum:", sum_c)
print("Mean:", mean_c)
print("Max:", max_c)

Sum: tensor(15.)
Mean: tensor(3.)
Max: tensor(5.)


#### 4- Reshaping Operations

In [8]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
#print(tensor[1,1].item()) # element at 1, 1

reshaped_tensor1 = torch.reshape(tensor, (3, 2))
reshaped_tensor2 = tensor.reshape(-1, 2)
flattened_tensor = tensor.view(-1)
expanded_tensor = torch.unsqueeze(tensor, 0)
squeezed_tensor = torch.squeeze(expanded_tensor)

# Reshape the tensor using view
# Generally faster because it avoids copying data if the tensor is already contiguous.
if not tensor.is_contiguous():
    tensor = tensor.contiguous()
reshaped_tensor_view = tensor.view(3, 2)

print("Original Tensor:\n", tensor)
print("Reshaped Tensor:\n", reshaped_tensor1)
print("Reshaped Tensor using -1:\n", reshaped_tensor2)
print("Flattened Tensor:\n", flattened_tensor)
print("Expanded Tensor:\n", expanded_tensor)
print("Squeezed Tensor:\n", squeezed_tensor)
print("Reshaped Tensor using view:\n", reshaped_tensor_view)

Original Tensor:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
Reshaped Tensor:
 tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Reshaped Tensor using -1:
 tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Flattened Tensor:
 tensor([1., 2., 3., 4., 5., 6.])
Expanded Tensor:
 tensor([[[1., 2., 3.],
         [4., 5., 6.]]])
Squeezed Tensor:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
Reshaped Tensor using view:
 tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
